services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "64G"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_TYPE: "ide"
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
